package com.ngdc.compodynamics.dto;

import lombok.Data;

@Data
public class CodonBiasHotmapDTO {
    private Long id;
    private String organism;//
    private Double rscuAaa;
    private Double rscuAag;
    private Double rscuAat;
    private Double rscuAac;
    private Double rscuTaa;
    private Double rscuTag;
    private Double rscuTat;
    private Double rscuTac;
    private Double rscuAta;
    private Double rscuAtg;
    private Double rscuAtt;
    private Double rscuAtc;
    private Double rscuTta;
    private Double rscuTtg;
    private Double rscuTtt;
    private Double rscuTtc;
    private Double rscuGaa;
    private Double rscuGag;
    private Double rscuGat;
    private Double rscuGac;
    private Double rscuCaa;
    private Double rscuCag;
    private Double rscuCat;
    private Double rscuCac;
    private Double rscuGta;
    private Double rscuGtg;
    private Double rscuGtt;
    private Double rscuGtc;
    private Double rscuCta;
    private Double rscuCtg;
    private Double rscuCtt;
    private Double rscuCtc;
    private Double rscuAga;
    private Double rscuAgg;
    private Double rscuAgt;
    private Double rscuAgc;
    private Double rscuTga;
    private Double rscuTgg;
    private Double rscuTgt;
    private Double rscuTgc;
    private Double rscuAca;
    private Double rscuAcg;
    private Double rscuAct;
    private Double rscuAcc;
    private Double rscuTca;
    private Double rscuTcg;
    private Double rscuTct;
    private Double rscuTcc;
    private Double rscuGga;
    private Double rscuGgg;
    private Double rscuGgt;
    private Double rscuGgc;
    private Double rscuCga;
    private Double rscuCgg;
    private Double rscuCgt;
    private Double rscuCgc;
    private Double rscuGca;
    private Double rscuGcg;
    private Double rscuGct;
    private Double rscuGcc;
    private Double rscuCca;
    private Double rscuCcg;
    private Double rscuCct;
    private Double rscuCcc;
}
