package com.ngdc.compodynamics.dto;

import lombok.Data;

@Data
public class CodonHotmapDTO {
    private Long id;
    private String organism;//
    private Double observedAaa;
    private Double observedAag;
    private Double observedAat;
    private Double observedAac;
    private Double observedTaa;
    private Double observedTag;
    private Double observedTat;
    private Double observedTac;
    private Double observedAta;
    private Double observedAtg;
    private Double observedAtt;
    private Double observedAtc;
    private Double observedTta;
    private Double observedTtg;
    private Double observedTtt;
    private Double observedTtc;
    private Double observedGaa;
    private Double observedGag;
    private Double observedGat;
    private Double observedGac;
    private Double observedCaa;
    private Double observedCag;
    private Double observedCat;
    private Double observedCac;
    private Double observedGta;
    private Double observedGtg;
    private Double observedGtt;
    private Double observedGtc;
    private Double observedCta;
    private Double observedCtg;
    private Double observedCtt;
    private Double observedCtc;
    private Double observedAga;
    private Double observedAgg;
    private Double observedAgt;
    private Double observedAgc;
    private Double observedTga;
    private Double observedTgg;
    private Double observedTgt;
    private Double observedTgc;
    private Double observedAca;
    private Double observedAcg;
    private Double observedAct;
    private Double observedAcc;
    private Double observedTca;
    private Double observedTcg;
    private Double observedTct;
    private Double observedTcc;
    private Double observedGga;
    private Double observedGgg;
    private Double observedGgt;
    private Double observedGgc;
    private Double observedCga;
    private Double observedCgg;
    private Double observedCgt;
    private Double observedCgc;
    private Double observedGca;
    private Double observedGcg;
    private Double observedGct;
    private Double observedGcc;
    private Double observedCca;
    private Double observedCcg;
    private Double observedCct;
    private Double observedCcc;
}
